### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by mathias-goebel** [subugoe/rdd-technical-reference#4]
It seems to me, that there is not a clear definition for ”test coverage”. [en.wikipedia.org](https://en.wikipedia.org/w/index.php?title=Test_coverage&redirect=no) redirects from test coverage to fault coverage »There are many kinds of test coverage«; [de.wikipedia.org](https://de.wikipedia.org/w/index.php?title=Code_Coverage&redirect=no) redirects from code coverage to test coverage. Especially when there is no common definition, the one that is applied here should be available. may be this leads to a glossary added to the document. Opinions?

**Comment by mweidling** [comment]
Thumbs up for a glossary.
There are many kinds of test coverage, indeed, since it depends on which level of testing you are referring to (unit level, integration level, ...). For each of these levels (and different test methods like black/white box testing) coverage is defined differently. What I originally meant (I think I was the one introducing the term) was coverage in unit testing which means that every method/function/unit has at least one test (preferrably more to cover different input data).

**Comment by ubbo** [comment]
clarification added to document 7f502b6
